# Generated by Django 5.2.6 on 2025-09-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подраздел электрики')),
            ],
            options={
                'verbose_name': 'Электрика',
                'verbose_name_plural': 'Электрика',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подраздел газового оборудования')),
            ],
            options={
                'verbose_name': 'Газовое оборудование',
                'verbose_name_plural': 'Газовое оборудование',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_name', models.CharField(max_length=50, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['rubric_name'],
            },
        ),
        migrations.CreateModel(
            name='ElectroProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='electro/', verbose_name='Фото товара')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.electro', verbose_name='Электрика')),
            ],
            options={
                'verbose_name': 'Товар раздела электрики',
                'verbose_name_plural': 'Товары раздела электрики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gas/', verbose_name='Фото товара')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.gas', verbose_name='Газовое оборудование')),
            ],
            options={
                'verbose_name': 'Товар раздела газового оборудования',
                'verbose_name_plural': 'Товары раздела газового оборудования',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gas',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.rubric', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='electro',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.rubric', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='Santeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Подраздел сантехники')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.rubric', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Сантехника',
                'verbose_name_plural': 'Сантехника',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SantehProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='santeh/', verbose_name='Фото товара')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.santeh', verbose_name='Сантехника')),
            ],
            options={
                'verbose_name': 'Товар раздела сантехники',
                'verbose_name_plural': 'Товары раздела сантехники',
                'ordering': ['title'],
            },
        ),
    ]
