# Generated by Django 5.2.6 on 2025-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroproduct',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код наименования'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код наименования'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код наименования'),
        ),
    ]
