# Generated by Django 5.2.6 on 2025-10-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0002_electroproduct_code_gasproduct_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electro',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Электрика"', 'verbose_name_plural': 'Раздел "Электрика"'},
        ),
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Газовое оборудование"', 'verbose_name_plural': 'Раздел "Газовое оборудование"'},
        ),
        migrations.AlterModelOptions(
            name='santeh',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Сантехника"', 'verbose_name_plural': 'Раздел "Сантехника"'},
        ),
    ]
