# Generated by Django 5.2.6 on 2025-10-10 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Введите только буквы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Введите только буквы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Фамилия'),
        ),
    ]
