# Generated by Django 5.2.6 on 2025-10-10 19:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0005_alter_order_first_name_alter_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY', verbose_name='Телефон (+375 ХХ ХХХХХХХ)'),
        ),
    ]
