# Generated by Django 5.2.6 on 2025-10-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('electroproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.electroproduct', verbose_name='Номер товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.order', verbose_name='Номер заказа')),
            ],
        ),
        migrations.AddField(
            model_name='electroproduct',
            name='order',
            field=models.ManyToManyField(through='esg.ElectroOrder', to='esg.order', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='GasOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('gasproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.gasproduct', verbose_name='Номер товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.order', verbose_name='Номер заказа')),
            ],
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='order',
            field=models.ManyToManyField(through='esg.GasOrder', to='esg.order', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='SantehOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.order', verbose_name='Номер заказа')),
                ('santehproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.santehproduct', verbose_name='Номер товара')),
            ],
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='order',
            field=models.ManyToManyField(through='esg.SantehOrder', to='esg.order', verbose_name='Заказ'),
        ),
    ]
