# Generated by Django 4.2.25 on 2025-10-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0007_electroorder_electroproduct_order_gasorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
