# Generated by Django 4.2.25 on 2025-10-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Газификация"', 'verbose_name_plural': 'Раздел "Газификация"'},
        ),
    ]
