# Generated by Django 4.2.25 on 2025-10-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0009_alter_gas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Газовое оборудование"', 'verbose_name_plural': 'Раздел "Газовое оборудование"'},
        ),
    ]
