# Generated by Django 5.2.7 on 2025-10-16 11:39

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0010_alter_gas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Введите только буквы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY', verbose_name='Телефон (+375 ХХ ХХХХХХХ)')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Ваше сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.BooleanField(default=False, verbose_name='Статус сообщения')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['-rubric_name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
