# Generated by Django 5.2.6 on 2025-10-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0011_feedback_alter_rubric_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
