# Generated by Django 5.2.6 on 2025-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0013_electroorder_total_cost_gasorder_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Тема'),
        ),
    ]
