# Generated by Django 5.2.6 on 2025-10-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0014_alter_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroproduct',
            name='status_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='electroproduct',
            name='status_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='status_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='status_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='status_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='status_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
    ]
