# Generated by Django 5.2.6 on 2025-10-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0015_electroproduct_status_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electroproduct',
            options={'ordering': ['title'], 'verbose_name': 'Товар раздела"Электрика"', 'verbose_name_plural': 'Товары раздела "Электрика"'},
        ),
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['title'], 'verbose_name': 'Раздел "Газификация"', 'verbose_name_plural': 'Раздел "Газификация"'},
        ),
        migrations.AlterModelOptions(
            name='gasproduct',
            options={'ordering': ['title'], 'verbose_name': 'Товар раздела "Газификация"', 'verbose_name_plural': 'Товары раздела "Газификация"'},
        ),
        migrations.AlterModelOptions(
            name='santehproduct',
            options={'ordering': ['title'], 'verbose_name': 'Товар раздела "Сантехника"', 'verbose_name_plural': 'Товары раздела "Сантехника"'},
        ),
        migrations.AlterField(
            model_name='gas',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Подраздел газификации'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg.gas', verbose_name='Газификация'),
        ),
    ]
