# Generated by Django 5.2.6 on 2025-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0016_alter_electroproduct_options_alter_gas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroproduct',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
