# Generated by Django 5.2.6 on 2025-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0017_electroproduct_counter_gasproduct_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='order',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
