# Generated by Django 5.2.6 on 2025-10-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0018_feedback_agreement_order_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agreement',
            field=models.BooleanField(verbose_name='Я даю согласие на обработку персональных данных'),
        ),
    ]
