# Generated by Django 5.2.6 on 2025-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0019_alter_order_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='name_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='rubric_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название раздела'),
        ),
    ]
