# Generated by Django 5.2.6 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0020_rubric_name_translit_alter_rubric_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
    ]
