# Generated by Django 5.2.6 on 2025-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0021_alter_rubric_name_translit'),
    ]

    operations = [
        migrations.AddField(
            model_name='electro',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AddField(
            model_name='electroproduct',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AddField(
            model_name='gas',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AddField(
            model_name='santeh',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='title_translit',
            field=models.CharField(default='', max_length=50, verbose_name='Название латиницей'),
        ),
    ]
