# Generated by Django 5.2.6 on 2025-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0022_electro_title_translit_electroproduct_title_translit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electro',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='santeh',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
    ]
