# Generated by Django 5.2.6 on 2025-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0023_alter_electro_title_translit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electroproduct',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='santehproduct',
            name='title_translit',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название латиницей'),
        ),
    ]
