# Generated by Django 5.2.6 on 2025-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0024_alter_electroproduct_title_translit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electro',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел электрики'),
        ),
        migrations.AlterField(
            model_name='electro',
            name='title_translit',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел газификации'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='title_translit',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name_translit',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название латиницей'),
        ),
        migrations.AlterField(
            model_name='santeh',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел сантехники'),
        ),
        migrations.AlterField(
            model_name='santeh',
            name='title_translit',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название латиницей'),
        ),
    ]
