# Generated by Django 5.2.6 on 2025-11-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0026_alter_electroproduct_title_translit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electroproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='electro/', verbose_name='Фото товара на странице'),
        ),
        migrations.AddField(
            model_name='gasproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='gas/', verbose_name='Фото товара на странице'),
        ),
        migrations.AddField(
            model_name='santehproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='santeh/', verbose_name='Фото товара на странице'),
        ),
        migrations.AlterField(
            model_name='electroproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='electro/', verbose_name='Фото товара на карточке'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gas/', verbose_name='Фото товара на карточке'),
        ),
        migrations.AlterField(
            model_name='santehproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='santeh/', verbose_name='Фото товара на карточке'),
        ),
    ]
