# Generated by Django 5.2.6 on 2025-11-13 08:50

import esg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0027_electroproduct_photo_big_gasproduct_photo_big_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electroproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='electro/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на карточке'),
        ),
        migrations.AlterField(
            model_name='electroproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='electro/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на странице'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gas/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на карточке'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='gas/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на странице'),
        ),
        migrations.AlterField(
            model_name='santehproduct',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='santeh/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на карточке'),
        ),
        migrations.AlterField(
            model_name='santehproduct',
            name='photo_big',
            field=models.ImageField(blank=True, null=True, upload_to='santeh/', validators=[esg.models.validate_image_extension], verbose_name='Фото товара на странице'),
        ),
    ]
