# Generated by Django 5.2.6 on 2026-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0028_alter_electroproduct_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electro',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел'),
        ),
        migrations.AlterField(
            model_name='gasproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='santeh',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подраздел'),
        ),
    ]
